#!/bin/sh
poolf $1                                                                \
        | awk '{printf "%s %s\n", $0, $0}'                              \
        | sed -e 's,https://[^ ]*/,,'                                   \
        | nl -nrz -s'	' -w5                                           \
        | sed -e 's,\t,_,'                                              \
        | awk '{system("wget --limit-rate=500K -O " $1 " " $2 )}'
